"""add membership & limits

Revision ID: 5a96a4f8a887
Revises: 
Create Date: 2025-08-20 15:27:19.325265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a96a4f8a887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('max_execs', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('code', name=op.f('uq_memberships_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_model_vendor', sa.String(length=20), nullable=True),
    sa.Column('last_model_name', sa.String(length=50), nullable=True),
    sa.Column('last_score', sa.Integer(), nullable=True),
    sa.Column('last_exec_id', sa.Integer(), nullable=True),
    sa.Column('last_analysis_at', sa.DateTime(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('exec_limit_override', sa.Integer(), nullable=True),
    sa.Column('execs_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_users_membership_id_memberships')),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_users'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name=op.f('fk_comments_email_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('uploaded_filename', sa.Text(), nullable=True),
    sa.Column('uploaded_ext', sa.String(length=10), nullable=True),
    sa.Column('uploaded_size', sa.Integer(), nullable=True),
    sa.Column('resume_lang', sa.String(length=5), nullable=True),
    sa.Column('jd_lang', sa.String(length=5), nullable=True),
    sa.Column('model_vendor', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name=op.f('fk_executions_email_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    op.drop_table('comments')
    op.drop_table('users')
    op.drop_table('memberships')
    # ### end Alembic commands ###
